#Permissions:
#  Reload gui - gui.reload

General:
  updateInterval: 2000

Data:
  HologramsDisplay:
    - "BWLobby:BWArensDuo"
    - "BWArensDuo"

Enable:
  Guis: true
  Items: true
  HologramsDisplay: true
  PlaceHolderApi: true

AnimationTime: 200
ClearInventoryOnJoin: true
ReplaceItemOnJoin: true