name: TGS
version: ${project.version}
main: me.towercraft.TGS
api-version: 1.13
author: Armatura
description: Displays the server dynamically in Gui
website: TowerCraft.me

commands:
  gui:
  connect: