Duo:
  location: world, -111.500, 47.900, 1351.500
  lines:
  - '&eРежим: &e&lDuo'
  - '&7Играют:'
shop:
  location: world, -87.300, 46.700, 1361.550
  lines:
  - '&e&lTowerShop'
tutorial:
  location: world, -98.522, 46.700, 1357.491
  lines:
  - '&eТуториал'
Team:
  location: world, -109.517, 47.900, 1347.501
  lines:
  - '&eРежим: &e&lSquad'
  - '&7Играют:'
Solo:
  location: world, -109.432, 47.900, 1355.497
  lines:
  - '&eРежим: &e&lSolo'
  - '&7Играют:'
