#Permissions:
#  Reload gui - gui.reload

General:
  updateInterval: 2000
  DefaultLanguage: "ru" # ru or en or...

Data:
  HologramsDisplay:
    - "BWLobby:BWArensDuo"
    - "BWArensDuo"

Enable:
  Gui: true
  Items: true
  HologramsDisplay: true
  PlaceHolderApi: true

AnimationTime: 20
ClearInventoryOnJoin: true