name: TowerGuiSystem
version: 0.10.0
main: com.towercraft.TowerGuiSystem
api-version: 1.13
authors: [Armatura, Shaytir]
description: Displays the server dynamically in Gui
website: TowerCraft.site

commands:
  gui:
  connect: