name: TowerGuiSystem
version: 0.4-BETA
main: com.towercraft.TowerGuiSystem
api-version: 1.13
authors: [ScrRnDeR]
description: Выводит сервера динамически в Гуи
website: TowerCraft.site

commands:
  gui:
  connect: