name: TowerGuiSystem
version: 0.9
main: com.towercraft.TowerGuiSystem
api-version: 1.13
authors: [Armatura]
description: Displays the server dynamically in Gui
website: TowerCraft.site

commands:
  gui:
  connect:
  hg: